services:
- postgresql
before_script:
 - psql -c 'create database sorteiotec;' -U postgres
 - psql -U postgres -d sorteiotec -f script/database/create_tables.sql                 
 - psql -U postgres -d sorteiotec -f script/database/insert_records.sql

language: java
jdk:
- oraclejdk8
script: mvn clean verify -DskipTests=false -DskipITs=false -DskipSTs=false
